# general settings
name: 009_ESRGANRS_x4_f64b23_UM2018_UM2018_128_400k_B16G1
model_type: ESRGANModelRS
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: UM2018_UM2018_128_train
    type: RSPairedImageDataset
    dataroot_gt: datasets/UM2018_UM2018_128/train/targets
    dataroot_lq: datasets/UM2018_UM2018_128/train/inputs
    meta_info_file: basicsr/data/meta_info/meta_info_UM2018_UM2018_128.txt
    filename_tmpl: '{}'
    io_backend:
      type: disk
    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 1
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: UM2018_UM2018_128_val
    type: RSPairedImageDataset
    dataroot_gt: datasets/UM2018_UM2018_128_div8/valid/targets/
    dataroot_lq: datasets/UM2018_UM2018_128_div8/valid/inputs/
    meta_info_file: basicsr/data/meta_info/meta_info_UM2018_UM2018_128_div8_valid.txt
    io_backend:
      type: disk

rs_options:
  datasets:
    gt_rescale_val: 10000
    lq_rescale_val: 10000
    gt_dtype: int16
    lq_dtype: int16
    gt_clip: true
    lq_clip: true

# network structures
network_g:
  type: RRDBNet
  num_in_ch: 4
  num_out_ch: 4
  num_feat: 64
  num_block: 23

network_d:
  type: VGGStyleDiscriminator
  num_in_ch: 4
  num_feat: 64

# path
path:
  pretrain_network_g: experiments/006_RRDBNetRS_PSNR_x4_f64b23_UM2018_UM2018_128_100000k_B16G1/models/net_g_100000.pth
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [50000, 100000, 200000, 300000]
    gamma: 0.5

  total_iter: 400000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: !!float 1e-2
    reduction: mean
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv5_4': 1  # before relu
    vgg_type: vgg19
    use_input_norm: true
    range_norm: false
    perceptual_weight: 1.0
    style_weight: 0
    criterion: l1
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 5e-3

  net_d_iters: 1
  net_d_init_iters: 0

# validation settings
val:
  val_freq: 1000
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr_rs
      crop_border: 4
      test_y_channel: false
      max_pixel: 10000

# logging settings
logger:
  print_freq: 10
  save_checkpoint_freq: 20000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
