# general settings
name: 004_EDSRRS_Lx4_f256b32_PS_UM2020_128_100000k_B16G1
model_type: SRModelRS
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: PS_UM2020_128_train
    type: RSPairedImageDataset
    dataroot_gt: datasets/PS_UM2020_128/train/targets
    dataroot_lq: datasets/PS_UM2020_128/train/inputs
    meta_info_file: basicsr/data/meta_info/meta_info_PS_UM2020_128.txt
    filename_tmpl: '{}'
    io_backend:
      type: disk
    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 1
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: PS_UM2020_128_div8_val
    type: RSPairedImageDataset
    dataroot_gt: datasets/PS_UM2020_128_div8/valid/targets/
    dataroot_lq: datasets/PS_UM2020_128_div8/valid/inputs/
    meta_info_file: basicsr/data/meta_info/meta_info_PS_UM2020_128_div8_valid.txt
    io_backend:
      type: disk

rs_options:
  datasets:
    gt_rescale_val: 10000
    lq_rescale_val: 10000
    gt_dtype: int16
    lq_dtype: uint16
    gt_clip: true
    lq_clip: true

# network structures
network_g:
  type: EDSRRS
  num_in_ch: 4
  num_out_ch: 4
  num_feat: 256
  num_block: 32
  upscale: 4
  res_scale: 0.1
  img_range: 10000.
  bgrnir_mean: [0.0614, 0.0914, 0.1265, 0.2484]

# path
path:
  pretrain_network_g: experiments/003_EDSRRS_Lx4_f256b32_UM2018_UM2018_128_100000k_B16G1/models/net_g_100000.pth
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0 #0.999
  optim_g:
    type: Adam
    lr: 0.0001 #!!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [66666]
    gamma: 0.5

  total_iter: 100000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: 1000 #21537 #!!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr_rs
      crop_border: 4
      test_y_channel: false
      max_pixel: 10000

# logging settings
logger:
  print_freq: 10
  save_checkpoint_freq: 20000 #!!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
